### ISSUE TITLE
报错 TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by somnifex** [rootlexblog/hexo-ai-excerpt#2]
```bash
ERROR Plugin load failed: hexo-ai-excerpt
TypeError: require(...) is not a function
    at C:\Users\HowieWu\Desktop\MyBlog\node_modules\hexo-ai-excerpt\index.js:2:32
    at C:\Users\HowieWu\Desktop\MyBlog\node_modules\hexo\dist\hexo\index.js:248:20
    at tryCatcher (C:\Users\HowieWu\Desktop\MyBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\HowieWu\Desktop\MyBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\HowieWu\Desktop\MyBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\HowieWu\Desktop\MyBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\HowieWu\Desktop\MyBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\HowieWu\Desktop\MyBlog\node_modules\bluebird\js\release\async.js:93:12)        
    at _drainQueue (C:\Users\HowieWu\Desktop\MyBlog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\HowieWu\Desktop\MyBlog\node_modules\bluebird\js\release\async.js:102:5)     
    at Async.drainQueues (C:\Users\HowieWu\Desktop\MyBlog\node_modules\bluebird\js\release\async.js:15:14)      
    at process.processImmediate (node:internal/timers:476:21)
```
请问下这个是什么原因呢，我在_config.yml中加入了
```yaml
# AI摘要
aiexcerpt:
  default_enable: true
  custom: true
  api: https://XXXX/v1/chat/completions
  token: sk-XXXXXXXX
  model: 
  prompt: '你是一个摘要生成工具，你需要解释我发送给你的内容，不要换行，不要超过200字，只需要介绍文章的内容，不需要提出建议和缺少的东西。请用中文回答，输出的内容开头为“ai: 这篇文章介绍了”'
  ignoreEl: [
    'table', 'pre', 'figure'
  ]
  max_token: 2000
```
